config/routes.rb
Rails.application.routes.draw do
	root "recipes#index"

  resources :recipes
	resources :ingredients
	post 'find_recipe', to: 'recipes#find_recipe'

	devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :recipes
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord

	has_many :recipes_ingredients
	has_many :recipes, through: :recipes_ingredients

  accepts_nested_attributes_for :recipes_ingredients

end

app/models/recipe.rb
class Recipe < ApplicationRecord
	mount_uploader :image, ImageUploader
	belongs_to :category
	has_many :recipes_ingredients
	has_many :ingredients, through: :recipes_ingredients
  has_many :steps

  accepts_nested_attributes_for :ingredients,
                                reject_if: proc { |a| a['title'].blank? },
                                allow_destroy: true

  accepts_nested_attributes_for :steps,
                                reject_if: proc { |a| a['step'].blank? },
                                allow_destroy: true

  validates :title, :description, :image, presence: true

  def ingredients_attributes=(ingredients_params)
    new_ingredients_list = ingredients_params.select { |id, param| param[:_destroy] == 'false' && param[:title].length != 0 }
    @recipe_ingred = []
    self.ingredients = new_ingredients_list.map do |id, ingr|
      recipe_ingred = ingr[:recipes_ingredients_attributes]['0'] if ingr[:recipes_ingredients_attributes].present?
      new_ingred = self.ingredients.where(title: ingr[:title].strip).first_or_create!
      new_ingred.recipes_ingredients.first.update_attributes(quantity: recipe_ingred['quantity'])
      new_ingred
    end
  end

end

app/models/recipes_ingredient.rb
class RecipesIngredient < ApplicationRecord
  belongs_to :recipe, :dependent => :destroy
  belongs_to :ingredient, :dependent => :destroy
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :ingredient_find, only: [:show, :edit, :destroy, :update]

  def index
    @ingredients = Ingredient.all.order('title ASC')
  end

  def show
  end

  def edit

  end

  def update
    if  @ingredient.update_attributes(ingredients_params)
      redirect_to action: "index", notice: 'Игредиент успешно изменен'
    else
      render :edit
    end
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredients_params)
    if @ingredient.save
      redirect_to action: "index", notice: 'Ингредиент успешно создан'
    else
      render :new
    end
  end

  private

  def ingredient_find
    @ingredient = Ingredient.find(params[:id])
  end

  def ingredients_params
    params.require(:ingredient)
    .permit(:title, :proteins, :fats, :carbohydrates, :calories)
  end
end

app/controllers/ingredients_recipes_controller.rb
class IngredientsRecipesController < ApplicationController
  before_action :ingredient_find, only: [:show, :edit, :destroy, :update]

  def index
  end

  def show
  end

  def new
    @ingredient = Recipe.new
  end

  private

  def ingredient_find
  end

  def ingredients_params

  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :recipe_find, only: [:show, :edit, :destroy, :update]
  def index
  	@recipes = []
  	@recipes << Recipe.where(category: 1).order("RANDOM()").take(3)
  	@recipes << Recipe.where(category: 2).order("RANDOM()").take(3)
  	@categories = Category.all
  end

  def show
  	@ingredients = @recipe.ingredients
  end

  def new
  	@recipe = Recipe.new
  end

	def create
		@recipe = Recipe.new(recipe_params)
		if @recipe.save
			redirect_to @recipe, notice: 'Рецепт успешно создан'
		else
			render :new
		end
	end

  def edit

  end

  def update
    if  @recipe.update_attributes(recipe_params)
  		redirect_to @recipe, notice: 'Рецепт успешно изменен'
  	else
  		render :edit
  	end
  end

  def destroy
    @recipe.destroy
    redirect_to root_path, notice: 'Рецепт успешно удален'
  end

  def find_recipe
    @result = Recipe.where('description LIKE ?', "%#{params[:textValue]}%").take(10)
    render partial: 'result'
  end

  private

  def recipe_find
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
		params.require(:recipe)
    .permit(:title,
            :description,
            :img,
            :category_id,
            :time,
            :portion,
            :image,
            ingredients_attributes: [:id, :title, :_destroy, recipes_ingredients_attributes: [:id, :quantity]],
            steps_attributes: [:id, :step, :_destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/categories/_category.html.haml
.category
	%div= image_tag category.image || "shawarma.jpg", class: 'rounded float-left img-category'
	.name-category= category.name

app/views/ingredients/_form.html.haml
.form
  = form_for @ingredient, html: { multipart: true } do |f|
    - if @ingredient.errors.any?
      = @ingredient.errors.count
      - @ingredient.errors.full_messages.each do |msg|
        %li= msg

    .form-group.row
      = f.label :title, class: 'col-sm-2 col-form-label'
      .col-sm-10
        = f.text_field :title, class: 'form-control'

    .form-group.row
      = f.label :proteins, class: 'col-sm-2 col-form-label'
      .col-sm-10
        = f.text_field :proteins, class: 'form-control'

    .form-group.row
      = f.label :fats, class: 'col-sm-2 col-form-label'
      .col-sm-10
        = f.text_field :fats, class: 'form-control'

    .form-group.row
      = f.label :carbohydrates, class: 'col-sm-2 col-form-label'
      .col-sm-10
        = f.text_field :carbohydrates, class: 'form-control'

    .form-group.row
      = f.label :calories, class: 'col-sm-2 col-form-label'
      .col-sm-10
        = f.text_field :calories, class: 'form-control'

      = f.submit 'Сохранить', class: 'btn btn-success'

app/views/ingredients/edit.html.haml
= render 'form'

app/views/ingredients/index.html.haml
%table.table.table-striped.table-hover
  %thead
    %tr
      %th{:scope => "col"}= link_to 'Добавить ингредиент', new_ingredient_path, class: 'badge badge-primary'
      %th{:scope => "col"} Белки
      %th{:scope => "col"} Жиры
      %th{:scope => "col"} Углеводы
      %th{:scope => "col"} Ккал
  %tbody
    - @ingredients.each do |ingred|
      %tr
        %th{:scope => "row"}= link_to ingred.title, edit_ingredient_path(ingred), class: 'btn btn-link'
        %td= ingred.proteins
        %td= ingred.carbohydrates
        %td= ingred.fats
        %td= ingred.calories

app/views/ingredients/new.html.haml
=render 'form'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title LegendaryRecipes
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .header.container-fluid
      %ul
        %li
          %a
            %div
              = link_to (image_tag "logo.png", class: 'logo'), root_path
        %li
          .input-group.input-group-sm
            %input.form-control#searchText{:placeholder => "Find a recipe", :type => "text"}
          #autocomplete{:width => "230"}
        %li
          %span#inputGroup-sizing-sm
            %img{:alt => "search", :height => "23", :src => "https://images.media-allrecipes.com/ar-images/icons/NavSearchIcon.svg", :width => "23"}
      .sign
        - if user_signed_in?
          = link_to "Выход", destroy_user_session_path, method: :delete, class: "btn btn-warning link-nav"
          = link_to 'new', new_recipe_path
        - else
          = link_to "Вход", new_user_session_path, class: "btn btn-warning link-nav"
          = link_to "Регистрация", new_user_registration_path, class: "btn btn-warning link-nav"
    - if current_page?(root_url)
      .container-fluid.category-recipes
        = render @categories

    .container-fluid.content
      - if current_page?(root_url)
        .carousel-container
          #carouselExampleIndicators.carousel.slide{"data-ride" => "carousel"}
            %ol.carousel-indicators
              %li.active{"data-slide-to" => "0", "data-target" => "#carouselExampleIndicators"}
              %li{"data-slide-to" => "1", "data-target" => "#carouselExampleIndicators"}
              %li{"data-slide-to" => "2", "data-target" => "#carouselExampleIndicators"}
            .carousel-inner.rounded
              .carousel-item.active.img_wrap
                =image_tag 'shawarma.jpg', class: 'd-block w-100 rounded'
                .carousel-caption.d-none.d-md-block
                  %h5 Название
                  %p Описание
              .carousel-item.img_wrap
                =image_tag 'pork.jpg', class: 'd-block w-100 rounded'
                .carousel-caption.d-none.d-md-block
                  %h5 Название
                  %p Описание
              .carousel-item.img_wrap
                =image_tag 'olivie.jpg', class: 'd-block w-100 rounded'
                .carousel-caption.d-none.d-md-block
                  %h5 Название
                  %p Описание
            %a.carousel-control-prev{"data-slide" => "prev", :href => "#carouselExampleIndicators", :role => "button"}
              %span.carousel-control-prev-icon{"aria-hidden" => "true"}
              %span.sr-only Previous
            %a.carousel-control-next{"data-slide" => "next", :href => "#carouselExampleIndicators", :role => "button"}
              %span.carousel-control-next-icon{"aria-hidden" => "true"}
              %span.sr-only Next
      .container
        -flash.each do |name, msg|
          = content_tag :div, msg, class: "alert"

      = yield

app/views/recipes/_form.html.haml
.form
	= form_for @recipe, html: { multipart: true } do |f|
		- if @recipe.errors.any?
			= @recipe.errors.count
			- @recipe.errors.full_messages.each do |msg|
				%li= msg

		.form-group.row
			= f.label :title, class: 'col-sm-2 col-form-label'
			.col-sm-10
				= f.text_field :title, class: 'form-control'

		.form-group.row
			= f.label :description, class: 'col-sm-2 col-form-label'
			.col-sm-10
				= f.text_area :description, class: 'form-control text-area-description'

		.form-group.row
			= f.label :image, class: 'col-sm-2 col-form-label'
			.col-sm-10
				= f.file_field :image, class: 'form-control-file'

		.form-group.row
			= f.label :category, class: 'col-sm-2 col-form-label'
			.col-sm-10
				= f.collection_select :category_id, Category.order(:name), :id, :name, { include_blank: false }, { class: "form-control" }

		.form-group.row
			= f.label :time, class: 'col-sm-2 col-form-label'
			.col-sm-10
				= f.text_field :time, class: 'form-control'

		.form-group.row
			= f.label :portion, class: 'col-sm-2 col-form-label'
			.col-sm-10
				= f.text_field :portion, class: 'form-control'
		.row
			.col-md-6
				%h3.col-sm-2.col-form-label Шаги
				#steps.col-sm-10
					= f.fields_for :steps do |step|
						= render 'step_fields.html', f: step
					.links
						= link_to_add_association 'add steps', f, :steps, class: 'btn btn-success'
			.form-group

			.col-md-6
				%h3.col-sm-2.col-form-label Ингридиенты
				#ingredients.col-sm-10
					= f.fields_for :ingredients do |ingredient|
						= render 'ingredient_fields.html', f: ingredient
					.links
						= link_to_add_association 'add ingredient', f, :ingredients, class: 'btn btn-success'
			.form-group

			= f.submit 'сохранить', class: 'btn btn-success'

app/views/recipes/_ingredient_fields.html.haml
.form-inline.clearfix.form-group
  .nested-fields
    = f.text_field :title,  class: 'form-input form-control'
    - a = f.object.recipes_ingredients.exists? ? :recipes_ingredients : f.object.recipes_ingredients.build
    = f.fields_for :recipes_ingredients, a do |i|
      = i.text_field :quantity,  class: 'form-input form-control'
    = link_to_remove_association "Remove ingred", f, class: "btn btn-danger"

app/views/recipes/_result.html.haml
- if @result.present?
  .list-group
    - @result.each do |recipe|
      = link_to recipe.title, recipe_path(recipe),
        class: 'list-group-item list-group-item-action'
- else
  .list-group-item.list-group-item-action Нет результатов

app/views/recipes/_step_fields.html.haml
.form-inline.clearfix.form-group
  .nested-fields
    = f.text_field :step,  class: 'form-input form-control'
    = link_to_remove_association "Remove Step", f, class: "btn btn-danger"

app/views/recipes/edit.html.haml
= render 'form'

app/views/recipes/index.html.haml
- @recipes.each do |category|
  .title-category
    %strong= category.first&.category.name
  .row
    - category.each do |recipe|
      .col-md-4
        .recipe
          .image-wrapper
            = link_to (image_tag recipe.image.url(:thumb), class: 'card-img-top'), recipe_url(recipe.id) if recipe.image?
          .card-body
            %h5= recipe.title
            -#%p.card-text= truncate(recipe.description, :length => 160)

app/views/recipes/new.html.haml
= render 'form'

app/views/recipes/show.html.haml
.recipe
	#recipe_top.row
		.col-md-4
			= image_tag @recipe.image.url(:large), class: 'img-recipe-show' if @recipe.image?
		.col-md-8
			#recipe_info
				%h1= @recipe.title
				%p.description= @recipe.description
				%p
					Submitted by
					= '@recipe.user.email'

			.ingredients-header
				%div.rec-info
					.time-recieps= "Time: #{@recipe.time}"
					.count-portion= "Personas: #{@recipe.portion},"
	.row
		.col-md-6
			#steps
				%h2 Шаги
				%ul
					- @recipe.steps.each do |step|
						%li= step.step
		.col-md-6
			#ingredients
				%h2 Ингридиенты
				%ul
					- @ingredients.each do |ingredient|
						%tr
							%td= ingredient.title
							%td= ingredient.recipes_ingredients.first.quantity